# Generated by Django 5.2.4 on 2025-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionBasedAPI', '0002_rename_student_class_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.CharField(default='PCIU', max_length=100),
        ),
    ]
