# Generated by Django 5.2.4 on 2025-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionBasedAPI', '0003_student_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='Bd', max_length=100),
        ),
    ]
